language: node_js
branches:
  only:
    - master
    - feat/ci_cd
cache:
   directories:
    - node_modules
services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
jobs:
  include:
    - stage: build-docker-image
      script: 
        - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin 
        - docker build -t kristoyoyo/instant-search:${COMMIT} .
        - docker image push kristoyoyo/instant-search:${COMMIT}
  
    - stage: docker-scan
      script: 
        - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin 
        - docker scan kristoyoyo/instant-search:${COMMIT}
        # TODO use CI_COMMIT_SHORT_SHA travis equivalent instead of fixed version

    - stage: container-composition-analysis-trivy
      before_install:
        # Trivy related tasks
        - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
        - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
      script:
        - ./trivy --exit-code 0 --severity HIGH --no-progress kristoyoyo/instant-search:${COMMIT}
        - ./trivy --exit-code 1 --severity CRITICAL --no-progress kristoyoyo/instant-search:${COMMIT}
      cache:
        directories:
          - $HOME/.cache/trivy
      artifacts:
          name: "Container Scan Report ${COMMIT}"
          paths:
            - report.md
          expire_in: 7 days
          when: on_failure

    - stage: deploy-integration
      script:
        - echo "Deploy instant-search on a new env that use ArgoCD consist only to deploy project (argoproj.io/v1alpha1.AppProject) and application (argoproj.io/v1alpha1.Application)"

  allow_failures:
    - stage: container-composition-analysis-trivy