language: node_js
branches:
  only:
    - master
    - feat/ci_cd
cache:
   directories:
    - node_modules
services:
  - docker
jobs:
  include:
    - stage: build-docker-image
      script: 
        - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin 
        - docker build -t kristoyoyo/instant-search:v0.0.1 .
        - docker image push kristoyoyo/instant-search:v0.0.1
    - stage: docker-scan
      script: 
        - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin 
        - docker scan kristoyoyo/instant-search:v0.0.1